CREATE TABLE IF NOT EXISTS applicant_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  full_name VARCHAR(255),
  email VARCHAR(255),
  birth_place VARCHAR(255),
  birth_date VARCHAR(255),
  gender VARCHAR(20),
  phone_code VARCHAR(10),
  phone VARCHAR(20),
  address VARCHAR(255),
  kelurahan VARCHAR(255),
  kecamatan VARCHAR(255),
  city VARCHAR(255),
  province VARCHAR(255),
  postal_code VARCHAR(10),
  linkedin_url VARCHAR(255),
  avatar_url VARCHAR(255),
  cv_url VARCHAR(255),
  cv_file_name VARCHAR(255),
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR(100),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR (100),
  deleted_at TIMESTAMP,
  deleted_by VARCHAR(100) 
);