CREATE TABLE IF NOT EXISTS applicant_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "fullName" VARCHAR(255),
  "birthPlace" VARCHAR(255),
  "birthDate" VARCHAR(255),
  gender VARCHAR(255),
  "phoneCode" VARCHAR(10),
  phone VARCHAR(50),
  address VARCHAR(255),
  kelurahan VARCHAR(255),
  kecamatan VARCHAR(255),
  city VARCHAR(255),
  province VARCHAR(255),
  "postalCode" VARCHAR(10),
  "isSameAddress" BOOLEAN DEFAULT false,
  "linkedinUrl" VARCHAR(255),
  "avatarUrl" VARCHAR(255),
  "cvUrl" VARCHAR(255),
  "cvFileName" VARCHAR(255),
  "jobSource" VARCHAR(255),
  "updatedBy" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE
);