CREATE TABLE IF NOT EXISTS educations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  applicant_profile_id UUID REFERENCES applicant_profiles(id) ON DELETE CASCADE,
  level VARCHAR(255),
  country VARCHAR(255),
  institution VARCHAR(255),
  major VARCHAR(255),
  is_still_studying BOOLEAN DEFAULT false,
  start_day VARCHAR(10),
  start_month VARCHAR(10),
  start_year VARCHAR(10),
  end_day VARCHAR(10),
  end_month VARCHAR(10),
  end_year VARCHAR(10),
  gpa VARCHAR(10),
  gpa_scale VARCHAR(10),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES users(id),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES users(id),
  deleted_at TIMESTAMP,
  deleted_by UUID REFERENCES users(id)
 );