CREATE TABLE IF NOT EXISTS work_experiences (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company VARCHAR(255),
  industry VARCHAR(255),
  position VARCHAR(255),
  "employmentType" VARCHAR(255),
  "jobLevel" VARCHAR(255),
  "teamSize" VARCHAR(50),
  "startDay" VARCHAR(10),
  "startMonth" VARCHAR(10),
  "startYear" VARCHAR(10),
  "endDay" VARCHAR(10),
  "endMonth" VARCHAR(10),
  "endYear" VARCHAR(10),
  "isCurrentJob" BOOLEAN DEFAULT false,
  responsibilities TEXT,
  "leaveReason" VARCHAR(255),
  "referenceName" VARCHAR(255),
  "referencePosition" VARCHAR(255),
  "referencePhoneCode" VARCHAR(10),
  "referencePhone" VARCHAR(50),
  "referenceEmail" VARCHAR(255),
  "updatedBy" VARCHAR(255),
  "createdAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
  applicant_profile_id UUID REFERENCES applicant_profiles(id) ON DELETE CASCADE
);