CREATE TABLE IF NOT EXISTS jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID REFERENCES job_categories(id),
  employment_type_id UUID REFERENCES employment_types(id),
  status_id UUID REFERENCES job_statuses(id),
  job_location_id UUID REFERENCES job_locations(id),
  education_level_id UUID REFERENCES education_levels(id),
  department_id UUID REFERENCES departments(id),
  work_mode_id UUID REFERENCES work_modes(id),
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  requirements TEXT,
  responsibilities TEXT,
  benefits TEXT,
  min_salary NUMERIC(15,2),
  max_salary NUMERIC(15,2),
  currency_code VARCHAR(10),
  salary_type VARCHAR(20),
  vacancy_count INT NOT NULL DEFAULT 1,
  experience_min_years NUMERIC(4,1) DEFAULT 0,
  published_at TIMESTAMP,
  close_at TIMESTAMP,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES users(id),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES users(id),
  deleted_at TIMESTAMP,
  deleted_by UUID REFERENCES users(id)
);