CREATE TABLE IF NOT EXISTS jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id UUID REFERENCES job_categories(id) NOT NULL,
  employment_type_id UUID REFERENCES employment_types(id) NOT NULL,
  status_id UUID REFERENCES job_statuses(id) NOT NULL,
  job_location_id UUID REFERENCES job_locations(id) NOT NULL,
  education_level_id UUID REFERENCES education_levels(id) NOT NULL,
  department_id UUID REFERENCES departments(id) NOT NULL,
  work_mode_id UUID REFERENCES work_modes(id) NOT NULL,
  management_profile_id UUID REFERENCES management_profiles(id),
  title VARCHAR(200) NOT NULL,
  slug VARCHAR(220) NOT NULL UNIQUE,
  description TEXT NOT NULL,
  requirements TEXT NOT NULL,
  responsibilities TEXT NOT NULL,
  benefits TEXT,
  min_salary NUMERIC(15,2) NOT NULL,
  max_salary NUMERIC(15,2) NOT NULL,
  currency_code VARCHAR(10) NOT NULL,
  salary_type VARCHAR(20) NOT NULL,
  vacancy_count INT NOT NULL DEFAULT 1,
  experience_min_years NUMERIC(4,1) DEFAULT 0,
  published_at TIMESTAMP NOT NULL DEFAULT NOW(),
  close_at TIMESTAMP NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  created_by VARCHAR(100),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_by VARCHAR (100),
  deleted_at TIMESTAMP,
  deleted_by VARCHAR(100) 
);