export const PERMISSIONS = {
  JOB: {
    LIST: 'JOB_LIST',
    CREATE: 'JOB_CREATE',
    READ: 'JOB_READ',
    UPDATE: 'JOB_UPDATE',
    DELETE: 'JOB_DELETE',
  },

  APPLICANT: {
    LIST: 'APPLICANT_LIST',
    CREATE: 'APPLICANT_CREATE',
    READ: 'APPLICANT_READ',
    UPDATE: 'APPLICANT_UPDATE',
    DELETE: 'APPLICANT_DELETE',
  },

  APPLICATION: {
    LIST: 'APPLICATION_LIST',
    CREATE: 'APPLICATION_CREATE',
    READ: 'APPLICATION_READ',
    UPDATE: 'APPLICATION_UPDATE',
    DELETE: 'APPLICATION_DELETE',
  },

  MASTER_DATA: {
    LIST: 'MASTER_DATA_LIST',
    CREATE: 'MASTER_DATA_CREATE',
    READ: 'MASTER_DATA_READ',
    UPDATE: 'MASTER_DATA_UPDATE',
    DELETE: 'MASTER_DATA_DELETE',
  },

  ADMIN: {
    LIST: 'ADMIN_LIST',
    CREATE: 'ADMIN_CREATE',
    READ: 'ADMIN_READ',
    UPDATE: 'ADMIN_UPDATE',
    DELETE: 'ADMIN_DELETE',
  },
} as const;
